version: 2.1

orbs:
  docker: circleci/docker@0.5.1

workflows:
  version: 2
  build:
    jobs:
      - docker/publish:
          image: omisegoimages/toolbox-backup
          dockerfile: backup/Dockerfile
          path: backup
